#!/bin/bash
gv=0

models=${1-"kree_pbon_rf42 kree_pbon_rf32 kree_pbon_rf22 kree_pbon_rf22 kree_pbo_rf32 kree_pbo_rf22 kreemer_pbo2 kreemer_pbo kreemer_pbo3"}
#profiles1="1a.6 1a1.4 1a2.5  1b.6 1b1.4 1c.5 1c1.4 2b.13 2b1.6 2c.10 3.5 31.4 4.5 41.3 5.6 51.5 6.4"
profiles1="1a2.5 1b1.4 1b2.4 1c1.4 1c2.4 2b1.6 2b2.6 31.4 41.3 51.5 52.5 6.4"
profiles2="1a 1b 1c 2b 3 4 5 6"


odir=~/dokumente/manuscripts/platt_saf/figures/

m=kree_pbon_rf42
# figure 8
ld=29;p=32.1;pname=3_for_figure_8
mkdir -p $odir/$pname/;    rm $odir/$pname/*
pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3 1
gunzip -c plots_constrained_locfixed.$ld/$m.$p.0.ps.gz > $odir/$pname/combined.ps
pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3 0
cp plots_constrained_locfixed.$ld/iplots/$m.$p.0/* $odir/$pname/



# figure 2
ld=99;p=2a;pname=2_for_figure_2
mkdir -p $odir/$pname/;    rm $odir/$pname/*
pmany_invert_sol free.$ld 0 1 $m $p 3 1
gunzip -c plots_free.$ld/$m.$p.1.ps.gz > $odir/$pname/combined.ps
pmany_invert_sol free.$ld 0 1 $m $p 3 0
cp plots_free.$ld/iplots/$m.$p.1/* $odir/$pname/





# all profiles
ld=14
for p in 1a2.5 1b2.4 1c1.4 2b2.6 31.4 41.3 52.5 61.4 ;do
    pname=`echo $p | gawk '{if(substr($1,1,1)==1)print(substr($1,1,2));else print(substr($1,1,1))}'`
    rm plots_constrained_locfixed.$ld/iplots/$m.$p.0/*
    echo $p $pname
    pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3 1
#    exit

    mkdir -p $odir/$pname/
    rm $odir/$pname/*
    gunzip -c plots_constrained_locfixed.$ld/$m.$p.0.ps.gz > $odir/$pname/combined.ps
    
    pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3 0
    cp plots_constrained_locfixed.$ld/iplots/$m.$p.0/* $odir/$pname/
    
done


cd $odir
tar --create --gzip --verbose --file $HOME/tmp/for_john.tgz * 
cd -

exit

ld=14
two_models="kree_pbon_rf22 kree_pbon_rf32  kree_pbon_rf42"
for p in 1a2.5 1b2.4 1c1.4 2b2.6 31.4 41.3 52.5 61.4 ;do
    fs=""
    for m in $two_models;do
	pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3
	cp plots_constrained_locfixed.$ld/$m.$p.0.ps.gz  $HOME/tmp/
	gunzip -f $HOME/tmp/$m.$p.0.ps.gz  
	#gv $HOME/tmp/$m.$p.0.ps
	fs="$fs $HOME/tmp/$m.$p.0.ps"
    done
    epsmerge --paper letter -par --print --postscript \
	-x 3 --orientation Landscape $fs > $HOME/tmp/comb.$p.ps
    rm $fs
#    sleep 10
#    ps aux | grep gv | grep -v grep | grep -v many | gawk '{printf("kill %i\n",$4)}' | sh
done

exit






odir=~/dokumente/manuscripts/platt_saf/figures/

ld=14
for m in kree_pbon_rf22 kree_pbon_rf32  kree_pbon_rf42 ;do
    for p in 1a2.5 1b2.4 1c1.4 2b2.6 31.4 41.3 52.5 61.4 ;do
	pname=`echo $p | gawk '{if(substr($1,1,1)==1)print(substr($1,1,2));else print(substr($1,1,1))}'`
	echo $p $pname
	pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3 1
	if [ $m =  kree_pbon_rf22 ];then
	    mkdir -p $odir/$pname/
	    gunzip -c plots_constrained_locfixed.$ld/$m.$p.0.ps.gz > $odir/$pname/combined.ps
	    
	    pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3 0
	    cp plots_constrained_locfixed.$ld/iplots/$m.$p.0/* $odir/$pname/
	fi
    done
    
done

exit


cd $odir
tar --create --gzip --verbose --file $HOME/tmp/for_john.tgz * 
cd -

exit
ld=14
two_models="kreemer_pbo2  kree_pbo_rf22 kree_pbo_rf32"
for p in $profiles1;do
    fs=""
    for m in $two_models;do
	pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3
	cp plots_constrained_locfixed.$ld/$m.$p.0.ps.gz  $HOME/tmp/
	gunzip -f $HOME/tmp/$m.$p.0.ps.gz  
	#gv $HOME/tmp/$m.$p.0.ps
	fs="$fs $HOME/tmp/$m.$p.0.ps"
    done
    epsmerge --paper letter -par --print --postscript \
	-x 3 --orientation Landscape $fs > $HOME/tmp/comb.$p.ps
    rm $fs
#    sleep 10
#    ps aux | grep gv | grep -v grep | grep -v many | gawk '{printf("kill %i\n",$4)}' | sh
done

exit

ld=14
fs=""
model="kree_pbo_rf22"		# old
for p in 1a2.5 1b1.4 1c1.4 2b1.6;do
    pmany_invert_sol constrained_locfixed.$ld 0 0 $model $p 3
    cp plots_constrained_locfixed.$ld/$model.$p.0.ps.gz  $HOME/tmp/
    gunzip -f $HOME/tmp/$model.$p.0.ps.gz  

    fs="$fs $HOME/tmp/$model.$p.0.ps"
done
model="kree_pbon_rf22"		# new
for p in 1a2.5 1b2.4 1c1.4 2b2.6;do
    pmany_invert_sol constrained_locfixed.$ld 0 0 $model $p 3 
    cp plots_constrained_locfixed.$ld/$model.$p.0.ps.gz  $HOME/tmp/
    gunzip -f $HOME/tmp/$model.$p.0.ps.gz  
    fs="$fs $HOME/tmp/$model.$p.0.ps"
done
model="kree_pbo_rf22"		# old
for p in 31.4 41.3 51.5 6.4;do
    pmany_invert_sol constrained_locfixed.$ld 0 0 $model $p 3
    cp plots_constrained_locfixed.$ld/$model.$p.0.ps.gz  $HOME/tmp/
    gunzip -f $HOME/tmp/$model.$p.0.ps.gz  

    fs="$fs $HOME/tmp/$model.$p.0.ps"
done
model="kree_pbon_rf22"		# new
for p in 31.4 41.3 52.5 6.4;do
    pmany_invert_sol constrained_locfixed.$ld 0 0 $model $p 3
    cp plots_constrained_locfixed.$ld/$model.$p.0.ps.gz  $HOME/tmp/
    gunzip -f $HOME/tmp/$model.$p.0.ps.gz  
    fs="$fs $HOME/tmp/$model.$p.0.ps"
done


epsmerge --paper letter -par --print --postscript \
	-x 4 -y 2 --orientation Landscape $fs > $HOME/tmp/comb.oldnew.ps
rm $fs
#    sleep 10
#    ps aux | grep gv | grep -v grep | grep -v many | gawk '{printf("kill %i\n",$4)}' | sh


exit


for ld in 14 29;do
    for p in $profiles1;do
#	for m in kree_pbo_rf2 kree_pbo_rf22;do
	for m in $models;do
	    pmany_invert_sol constrained_locfixed.$ld 0 0 $m $p 3
	done
    done
done


exit

pmany_invert_sol constrained_locfixed.14 0 "0 1" "$models" "$profiles1"  $gv
pmany_invert_sol constrained_locfixed.29 0 "0 1" "$models" "$profiles1"  $gv

exit
pmany_invert_sol free.14 1 "1 3 5" "$models" "$profiles2" $gv
pmany_invert_sol free.29 1 "1 3 5" "$models" "$profiles2" $gv 


for ld in 14 29;do
    pmany_invert_sol constrained_locfixed.$ld 0 0 "$models " 1a1.4 3
    pmany_invert_sol constrained_locfixed.$ld 0 0 "$models " 1b1.4 3
    pmany_invert_sol constrained_locfixed.$ld 0 0 "$models " 1c1.4 3
    pmany_invert_sol constrained_locfixed.$ld 0 0 "$models " 2b1.6 3
    pmany_invert_sol constrained_locfixed.$ld 0 0 "$models " 31.4  3
    pmany_invert_sol constrained_locfixed.$ld 0 0 "$models " 41.3  3
    pmany_invert_sol constrained_locfixed.$ld 0 0 "$models " 51.5  3
done

combine_plots


